apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.environment }} 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}  
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  # Resources block from values.yaml
      imagePullSecrets:
        - name: myregistrykey

