apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simple-node-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-simple-node-app
