name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: olagunju
        password: princeoflife430

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: olagunju/simple-node-app:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAT6LU6HX5T5RB5PNV
        aws-secret-access-key: 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
        aws-region: us-west-2

    - name: Upload Helm chart to S3
      run: |
        helm package ./chart --destination ./
        aws s3 cp ./chart-0.1.0.tgz s3://helm-charts-bucket1/

    - name: Setup Kubectl and Update kubeconfig
      run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          aws eks update-kubeconfig --region us-west-2 --name kredi-cluster

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install simple-nodejs3 ./chart --namespace default --set image.repository=olagunju/chart --set image.tag=latest
        kubectl rollout status deployment/chart
