name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: olagunju
        password: princeoflife430

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: olagunju/simple-node-app:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAT6LU6HX56SBOTWVB
        aws-secret-access-key: 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
        aws-region: us-west-2

    - name: Upload Helm chart to S3
      run: |
        helm package ./chart --destination ./
        aws s3 cp ./chart-0.1.0.tgz s3://helm-chart-bucket1/

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install simple-nodejs2 ./chart --namespace default --set image.repository=olagunju/chart --set image.tag=latest
        kubectl rollout status deployment/chart
